/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_onlinecache_breakpad_NativeBreakpad */

#ifndef _Included_cn_onlinecache_breakpad
#define _Included_cn_onlinecache_breakpad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_onlinecache_breakpad_NativeBreakpad
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_onlinecache_breakpad_NativeBreakpad_nativeInit
  (JNIEnv *, jobject, jstring);

/*
  * Class:     cn_onlinecache_breakpad_NativeBreakpad
  * Method:    nativeTestCrash
  * Signature: * Signature: ()V
  */
 JNIEXPORT jint JNICALL Java_cn_onlinecache_breakpad_NativeBreakpad_nativeTestCrash
   (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
