/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_onlinecache_breakpad_NativeBreakpad */

#ifndef _Included_cn_onlinecache_breakpad
#define _Included_cn_onlinecache_breakpad
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_onlinecache_breakpad_NativeBreadpad
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_onlinecache_breakpad_NativeBreakpad_nativeInit
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
